function [pOpt, Info] = parameterEstimationProva(p, v, t, V1, V2)
%PARAMETERESTIMATIONPROVA
%
% Solve a parameter estimation problem for the Prova model.
%
% The function returns estimated parameter values, pOpt,
% and estimation termination information, Info.
%
% The input argument, p, defines the model parameters to estimate,
% if omitted the parameters specified in the function body are estimated.
%
% Modify the function to include or exclude new experiments, or
% to change the estimation options.
%
% Auto-generated by SPETOOL on 09-Feb-2020 17:55:22.
%

%% Open the model.
open_system('Prova')

%% Specify Model Parameters to Estimate
%
if nargin < 1
    p = [];
end

%% Define the Estimation Experiments
%

Exp = sdo.Experiment('Prova');

%%
% Specify the measured experiment output data.
Exp_Sig_Output = Simulink.SimulationData.Signal;
Exp_Sig_Output.Values    = timeseries(v,t);
Exp_Sig_Output.BlockPath = 'Prova/Cell';
Exp_Sig_Output.PortType  = 'outport';
Exp_Sig_Output.PortIndex = 1;
Exp_Sig_Output.Name      = 'Cell_Voltage';
Exp.OutputData = Exp_Sig_Output;

%%
% Specify the experiment initial states.
State = sdo.getStateFromModel('Prova',{'Prova/Cell/C1', 'Prova/Cell/C2'});
State(2).Free = false;
State(2).Value = V1;
State(4).Free = false;
State(4).Value = V2;
Exp.InitialStates = State;

%%
% Specify experiment specific parameters.
Param = sdo.getParameterFromModel('Prova',{'R0_est'});
Param(1).Minimum = 0;
Param(1).Maximum = 0.05;
Exp.Parameters = Param;

%%
% Create a model simulator from an experiment
Simulator = createSimulator(Exp);
%%
% Add experiment specific parameters/states to the list of parameters
% to estimate.
s = getValuesToEstimate(Exp);
p = [p; s];

%% Create Estimation Objective Function
%
% Create a function that is called at each optimization iteration
% to compute the estimation cost.
%
% Use an anonymous function with one argument that calls Prova_optFcn.
optimfcn = @(P) Prova_optFcn(P,Simulator,Exp);

%% Optimization Options
%
% Specify optimization options.
Options = sdo.OptimizeOptions;
Options.Method = 'lsqnonlin';
Options.OptimizedModel = Simulator;
Options.UseParallel = true;
[dirs, files] = sdo.getModelDependencies('Prova');
files = vertcat(files, 'C:\Users\PcElettronicaDynamis\Desktop\Mattia\parameterEstimationProva.m');
Options.ParallelFileDependencies = files;


%% Estimate the Parameters
%
% Call sdo.optimize with the estimation objective function handle,
% parameters to estimate, and options.
[pOpt,Info] = sdo.optimize(optimfcn,p,Options);

%%
% Update the experiments with the estimated parameter values.
Exp = setEstimatedValues(Exp,pOpt);

%% Update Model
%
% Update the model with the optimized parameter values.
sdo.setValueInModel('Prova',pOpt(1:0));
end

function Vals = Prova_optFcn(P,Simulator,Exp)
%PROVA_OPTFCN
%
% Function called at each iteration of the estimation problem.
%
% The function is called with a set of parameter values, P, and returns
% the estimation cost, Vals, to the optimization solver.
%
% See the sdoExampleCostFunction function and sdo.optimize for a more
% detailed description of the function signature.
%

%%
% Define a signal tracking requirement to compute how well the model
% output matches the experiment data.
r = sdo.requirements.SignalTracking(...
    'Method', 'Residuals');
%%
% Update the experiment(s) with the estimated parameter values.
Exp = setEstimatedValues(Exp,P);

%%
% Simulate the model and compare model outputs with measured experiment
% data.

F_r = [];
Simulator = createSimulator(Exp,Simulator);
Simulator = sim(Simulator);

SimLog = find(Simulator.LoggedData,get_param('Prova','SignalLoggingName'));
Sig = find(SimLog,Exp.OutputData.Name);

Error = evalRequirement(r,Sig.Values,Exp.OutputData.Values);
F_r = [F_r; Error(:)];

%% Return Values.
%
% Return the evaluated estimation cost in a structure to the
% optimization solver.
Vals.F = F_r;
end

function Data = getData(DataID)
%GETDATA
%
% Helper function to store data used by parameterEstimation_Prova.
%
% The input, DataID, specifies the name of the data to retrieve. The output,
% Data, contains the requested data.
%

switch DataID
    case 'Exp_Sig_Output_Value'
        t = [0; 0.02999999999883585; 0.04999999999563443; 0.05999999999767169; 0.08000000000174623;  ...
            0.09999999999854481; 0.1199999999953434; 0.1299999999973807; 0.1509999999980209;  ...
            0.1699999999982538];
        y = [4.175283; 4.186739; 4.186102; 4.186102; 4.188011; 4.187375; 4.186739; 4.188648;  ...
            4.186739; 4.187375];
        Data = timeseries(y,t);
end
end
